__author__ = "@Tssp"
__date__ = "01/10/20"
pot    = 'sin2'               # sin2 or cos2 expansion
n      = 6                    # Expansion order
Ix     = 7190                 # Laser intensity in mW/cm2 X
Iy     = 4993                 # Laser intensity in mW/cm2 Y
Iz     = 50                   # Laser intensity in mW/cm2 Z
wL     = 1000                 # Wavelength in nm
hbar   = 1                    # Planck reduced Constant
m      = 12789.3927072494     # Li mass in a.u
alpha  = 200                  # Polarization a.u
delta  = 50                   # Grid spacing
xmax   = 20000                # xmax
xmin   = -20000               # xmin
mode   = 'CM'                 # Compute mode: all or CM